version: '3.4'

services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    build:
      context: .
      dockerfile: ConferenceAttendees.API/Dockerfile
    ports:
      - "7038:7038"
    environment:
      - ASPNETCORE_URLS=http://*:7038
    depends_on: [mssql,seq_logs]
  conferenceattendees.mvc:
    image: ${DOCKER_REGISTRY-}conferenceattendeesmvc
    build:
      context: .
      dockerfile: ConferenceAttendees.MVC/Dockerfile
    ports:
      - "7058:7058"
    environment:
      - ASPNETCORE_URLS=http://*:7058
    depends_on:
      - conferenceattendees.api
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql2
    hostname: mssql
    environment: 
    # removing $ from password, because compose direct read have issue with it 
      - SA_PASSWORD=Str0ngPassword123
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1401:1433" 
  seq_logs:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5432:80"
    environment:
      - ACCEPT_EULA=Y
  

